# 27. JS 예외와 예외처리

: 에러를 컨트롤하는 매커니즘

: 발생가능한 에러를 미리 예측하고 그거를 처리할 수 있는 방법

<br>

#### [1. Error 객체]

----

: JS 내장 객체. 에러처리에 간편하게 사용 가능

```js
const err = new Error('invalid email');   // Error 인스턴스 만들면서 에러 메서지 지정 가능
```

```js
// 이메일 유효 검사 함수
function validateEmail(email) {
    return email.match(/@/) ?
        email :
    	new Error(`invalid email: ${email}`);
}
```

```js
// instanceof 연산자를 써서 Error 인스턴스 반환 확인
const email = "jane@doe.com";

const validatedEmail = validateEmail(email);
if (validatedEmail instanceof Error) {
    console.log(`Error : ${validatedEmail.message}`);
} else {
    console.log(`Valid email : ${validateEmail`);
}
```

<br>

#### [2. try/catch를 이용한 예외 처리]

----

: 위의 Error 객체를 사용한 예외 처리는 **예측 가능한 에러를 처리할때 사용**

: **예측하기 어려운 에러 발생시** try문 안에 있는 코드 실행중에 에러 발생하면 catch문으로 실행흐름 넘어간다.

:  에러 발생하지 않으면 catch 문 실행되지 않는다.

: 에러 발생시 catch블록에 숫자, 문자열등을 넘길수도 있지만 Error 인스턴스를 넘기는게 가장 편리

```js
try {
	// try 문
} catch(err) {
	//catch 문
}
```

<br>

#### [3. 에러 일으키기]

----

: 이를 이용해 일부로 특정 조건에 맞지 않으면 일부로 에러를 발생시켜 사용

```js
function billPay(amout, payee, account) {
    if(amount > account.balance)
        throw new Error("Insufficient funds");
    account.transfer(payee, amount);
}
```

<br>

#### [4. 예외 처리와 호출 스택]

----

- **호출 스택(call stack)**

  : 함수 a 가 함수 b를 호출하고, 함수 b가 함수 c를 호출할때, **함수 c가 실행 중에는 함수 a, b는 완료될수 없고 이렇게 완료되지 않은 함수가 쌓이는 것**

  : c에서 에러 발생시, **에러는 캐치될때까지 호출 스택을 따라 올라간다.**

  <br>

- **처리하지 않은 예외 (= 캐치하지 않은 예외)**

  : 발생한 에러를 어느 시점에서든 캐치안하면 JS 인터프리터는 프로그램을 멈춘다

  <br>

- **에러 캐치의 장점**

  : 호출 스택이 c에서 일어난 에러를 보고한다.

  : 거기에 b가 c를 호출했고, a가 b를 호출했다는 사실도 같이 알려준다.

<br>

#### [5. try ... catch ... finally]

----

: finally에 있는 문은 **에러 발생 유무와 관계없이 실행된다**

```js
try {
	// try문
} catch(err) {
	// catch문
} finally {
	// finally문
}
```

